<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{

    protected $guarded = [];
    protected static function boot()
    {
        parent::boot();// TODO: Change the autogenerated stub
        self::addGlobalScope('owner', function ($builder){
            $builder->with('owner');
        });
    }
    public function thread()
    {
        return $this->belongsTo(Thread::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function likes()
    {
        return $this->morphMany(User::class, 'likable');
    }

    public function like($userID)
    {
        return $this->likes()->attach($userID);
    }

    public function isLikable()
    {
        return $this->likes->where('user_id', auth()->user()->id)->count();
    }
}
