<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;

class Thread extends Model
{
    //
    use RecordsActivity;
    protected $guarded = [];
    protected static function boot()
    {
        parent::boot();// TODO: Change the autogenerated stub
        self::addGlobalScope('replyCount', function ($builder){
            $builder->withCount('replies');
        });
        self::deleting(function($thread){
            $thread->replies()->delete();
        });
    }



    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class)->withCount('likes');
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function scopeFilter($query, $filter)
    {
//        dd('aaa');
        $filter->apply($query);
    }

}
